import Head from "next/head";
import Block from "../components/BlockContainer/Block/Block";
import BlockContainer from "../components/BlockContainer/BlockContainer";
import { useSelector } from "react-redux";

export default function Home() {
  const currentVideos = useSelector((state) => state.videoResult.currentVideos);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlockContainer>
        {currentVideos?.map((block, index) => (
          <Block {...block} key={index} />
        ))}
      </BlockContainer>
    </div>
  );
}
